default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: dalton_app_development

test:
  <<: *default
  database: dalton_app_test

production:
  <<: *default
  database: dalton_app_production
  username: dalton_user
  password: <%= ENV['DALTON_APP_DATABASE_PASSWORD'] %>
