default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dalton_app_development

test:
  <<: *default
  database: dalton_app_test

production:
  adapter: postgresql
  encoding: unicode
  database: dalton_app_production
  pool: 5
  username: dalton
  password: root
  port: 5432 # default PostgreSQL port
